# This is a basic workflow to help you get started with Actions

name: Codewarrior

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Fetch SARIF - for example:
      # - Checkout the repository using `actions/checkout` if the SARIF file is committed. This example assumes the SARIF file is located at `sarif/findings.sarif` within the repository.
      #     - name: Checkout repository
      #       uses: actions/checkout@v2
      # - Fetch the SARIF file from your SAST tool. The vendor may already have a GitHub Action for this. This example assumes the SARIF file is fetched and saved to `sarif/findings.sarif`.
      #     - name: Download SARIF
      #       uses: vendor/sast-tool-sarif@v1
      #       with:
      #         user: ${{ secrets.USER }}
      #         key: ${{ secrets.KEY }}
      #         scan-id: ${{ secrets.SCAN_ID }}
      #         output-file: sarif/findings.sarif
      # - Convert a SAST tool report into SARIF. The vendor may already have a GitHub Action or script for this. This example assumes the converted SARIF file is located at `sarif/findings.sarif`.
      #     - name: Convert report to SARIF
      #       uses: vendor/sast-tool-sarif-converter@v1
      #       with:
      #         report-file: reports/sast-scan.xml
      #         output-file: sarif/findings.sarif

      - name: Add SCW Training
        uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
        with:
          inputSarifFile: sarif/findings.sarif
          outputSarifFile: sarif/findings.processed.sarif
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Import Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif/findings.processed.sarif
